### PR TITLE
Fixes a bug with _args being None if no additional argument is manual…

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
@hgromer

**Comment by KOLANICH** [comment]
Could you, please, mark this repo as "archived", if PRs are not welcome?

**Comment by tjkessler** [comment]
@KOLANICH,

With the recent overhaul, I'm requesting that any pull requests are resubmitted and pertain to the latest release version.

Best,
Travis

**Comment by KOLANICH** [comment]
Thanks for the info, will do when I have time.

**Pull request closed without merging**
