### PR TITLE
Added .editorconfig according to PEP 8

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by KOLANICH** [comment]
Could you, please, mark this repo as "archived", if PRs are not welcome?

**Comment by tjkessler** [comment]
@KOLANICH,

With the recent overhaul, I'm requesting that any pull requests are resubmitted and pertain to the latest release version.

Best,
Travis

**Comment by KOLANICH** [comment]
This one doesn't look like it requires to be resubmitted.

**Comment by tjkessler** [comment]
Agreed, I'll go ahead and merge this request.

**Pull request merged**
